### ISSUE TITLE
Tracis_CI not importing python package

### ISSUE THREAD

**Issue by Sylhare** [Sylhare/PyPrime#8]
The tests run perfectly locally but when on Travis Ci it reports me this error:
```
Traceback (most recent call last):
  File "test/test_pyprime.py", line 2, in <module>
    import app.pyprime as p
ImportError: No module named 'app'
```
As if the `app` package couldn't be found by Travis. I am going to investigate why.

**Comment by Sylhare** [comment]
This solution failed, the attempt was to use a higher level having
```
pyprime
|_ app
|_ tests
```

So that Travis would kmow where to take the package.

**Comment by Sylhare** [comment]
The setup.py failed and I received a:
```
Traceback (most recent call last):
  File "test/test_pyprime.py", line 2, in <module>
    import app.pyprime as p
ImportError: No module named 'app'
```

**Comment by Sylhare** [comment]
Adding this line `export PYTHONPATH=$PYTHONPATH:$(pwd)` in before_install seems to fix the problem as well:
```yml
before_install:
- "pip install -U pip"
- "export PYTHONPATH=$PYTHONPATH:$(pwd)"
```

**Comment by Sylhare** [comment]
So to finalize, I found a couple of solution

### Solution 1

The quick fix for me was to add this line export `PYTHONPATH=$PYTHONPATH:$(pwd)` inthe `.travis.yml`:
```yml
before_install:
- "pip install -U pip"
- "export PYTHONPATH=$PYTHONPATH:$(pwd)"
```

### Solution 2
Having a `setup.py` which should be the default option as it is the most elegant, configured like:
```python
from setuptools import setup, find_packages

setup(name='MyPythonProject',
      version='0.0.1',
      description='What it does',
      author='',
      author_email='',
      url='',
      packages=find_packages(),
     )
```

And then add this line in `.travis.yml`
```yml
before_install:
- "pip install -U pip"
- "python setup.py install"
```

### Solution 3

Change the layout of the project to have the test folder under the application one (the one with your core python code) such as:
```
.travis.yml
requirements.txt
app
|_ tests
|   |_ test_application.py
|_ application.py
```

And running the test in travis with coverage and nosetest like:
```yml
script:
    - nosetests --with-coverage --cover-package app
```
